### ISSUE TITLE
Smart Cover partially works

### ISSUE THREAD

**Issue by deadman96385** [CM-zenfone2/android_device_asus_moorefield_fhd_no_longer_used_use_Z00A_instead#5]
Currently the smart wake cover partially works it will wake up the phone when it's opened but it does not put the phone to sleep when its closed not a major bug just wanted you to be aware

**Comment by jrior001** [comment]
Thanks, I don't think anybody has looked at this yet. Pretty focused on core functions (audio/radio/camera) before we get to less critical features like this.

**Comment by deadman96385** [comment]
Yep no problem

**Comment by rafyvitto** [comment]
Anything usefull here https://github.com/thuutin/android_device_asus_a500cg ? SOC should be close enough to ours.

**Comment by deadman96385** [comment]
Going to try out those memory opts

**Comment by deadman96385** [comment]
They cause it not too boot

**Comment by deadman96385** [comment]
Fixed a while ago
